<?php

/**
 * @file contextly.install
 *
 * @author: dj 
 * created: 2019.03.15. - 8:28:41
 *
 * Contains contextly install hooks.
 */

use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Create contextly disabled column for node.
 */
function contextly_update_8000() {
  $field_storage_definition = _contextly_get_disabled_field_definition();

  \Drupal::entityDefinitionUpdateManager()
    ->installFieldStorageDefinition('contextly_disabled', 'node', 'node', $field_storage_definition);
}
