# Schema for Contextly module configuration.

contextly.settings:
  type: config_object
  label: 'Contextly settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    kit_cdn:
      type: boolean
      label: 'Contextly CDN'
    server_mode:
      type: string
      label: 'Server mode'
